### ISSUE TITLE
Automated Testing Script for PrestaShop Store Using Selenium

### ISSUE THREAD

**Issue by greedann** [greedann/Biznes-elektroniczny#3]
### Requirements

Develop an automated testing script for the PrestaShop store using **Selenium** ([Selenium Documentation](https://www.selenium.dev/documentation/en/)). The script should perform the following actions within a maximum execution time of **5 minutes**:

#### Script Actions
1. **Add Products to Cart**:
   - Add a total of 10 products to the cart in varying quantities.
   - Select products from **two different categories**.

2. **Product Search and Add to Cart**:
   - Search for a product by name.
   - From the search results, randomly select one product and add it to the cart.

3. **Remove Products from Cart**:
   - Remove **3 products** from the cart.

4. **Account Registration**:
   - Register a new user account.

5. **Cart Checkout**:
   - Complete the purchase for the items in the cart.

6. **Payment Method Selection**:
   - Select **"Cash on Delivery"** as the payment method.

7. **Carrier Selection**:
   - Choose one of the two available carriers.

8. **Order Confirmation**:
   - Confirm the order.

9. **Order Status Check**:
   - Verify the status of the order.

10. **VAT Invoice Download**:
    - Download the VAT invoice for the order.

**Comment by Puchinni** [comment]
sir yes sir. i accept the mission!!!
